In [1]:
import pandas as pd
path = "data/olist/" # caminho raiz até os arquivos *.csv
orders = pd.read_csv(path + "olist_orders_dataset.csv")

In [2]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [3]:
colunas = ["order_purchase_timestamp", "order_approved_at", "order_delivered_carrier_date", "order_delivered_customer_date", "order_estimated_delivery_date"]
orders[colunas] = orders[colunas].apply(pd.to_datetime)
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [4]:
orders['order_status'].describe()

count         99441
unique            8
top       delivered
freq          96478
Name: order_status, dtype: object

In [5]:
agrupado = orders.groupby('order_status').size()
agrupado

order_status
approved           2
canceled         625
created            5
delivered      96478
invoiced         314
processing       301
shipped         1107
unavailable      609
dtype: int64

In [6]:
### TEMPO DE ENTREGA REALIZADO - ESTIMADO ###
entregues = orders.loc[orders["order_status"] == "delivered"].copy()

entregues["delivered_in_days"] = (
    entregues["order_estimated_delivery_date"]
    - entregues["order_delivered_customer_date"]
).dt.days

entregues['delivered_in_days'].describe()
entregues['delivered_in_days']

count    96470.000000
mean        10.875889
std         10.182105
min       -189.000000
25%          6.000000
50%         11.000000
75%         16.000000
max        146.000000
Name: delivered_in_days, dtype: float64

In [7]:
mins = entregues.loc[entregues['delivered_in_days'] < 0]
med = entregues[(entregues['delivered_in_days'] > 0) & (entregues['delivered_in_days'] < 12)]
a=(entregues["delivered_in_days"] < 0).mean() * 100
a
num_pedidos = len(entregues)
num_pedidos_antes = len(mins)
num_pedidos_prazo = len(med)
print (f'{num_pedidos_antes/num_pedidos * 100} % de pedidos entregues antes do prazo')
print (f'{num_pedidos_prazo/num_pedidos * 100} % de pedidos entregues no prazo')
print(f'{(num_pedidos - (num_pedidos_antes + num_pedidos_prazo))/num_pedidos * 100} % de pedidos atrasados')

8.111693857667031 % de pedidos entregues antes do prazo
40.583345425900205 % de pedidos entregues no prazo
51.30496071643276 % de pedidos atrasados

In [8]:
import plotly.express as px

fig = px.histogram(
    entregues,
    x="delivered_in_days",  # atraso em dias
    nbins=100,
    title="Tempo de entrega dos pedidos em dias (Estimado - Realizado)"
)
fig.show()

In [9]:
top_10_atrasos = entregues['delivered_in_days'].to_frame()
top_10_atrasos.describe()

       delivered_in_days
count       96470.000000
mean           10.875889
std            10.182105
min          -189.000000
25%             6.000000
50%            11.000000
75%            16.000000
max           146.000000

In [10]:
### PEDIDOS NÃO ENTREGUES ###
nao_entregues = orders[orders['order_status'] != "delivered"]
nao_entregues

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaT,NaT,2017-05-09
44,ee64d42b8cf066f35eac1cf57de1aa85,caded193e8e47b8362864762a83db3c5,shipped,2018-06-04 16:44:48,2018-06-05 04:31:18,2018-06-05 14:32:00,NaT,2018-06-28
103,0760a852e4e9d89eb77bf631eaaf1c84,d2a79636084590b7465af8ab374a8cf5,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaT,NaT,2018-08-21
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaT,NaT,2017-10-03
154,6942b8da583c2f9957e990d028607019,52006a9383bf149a4fb24226b173106f,shipped,2018-01-10 11:33:07,2018-01-11 02:32:30,2018-01-11 19:39:23,NaT,2018-02-07
...,...,...,...,...,...,...,...,...
99283,3a3cddda5a7c27851bd96c3313412840,0b0d6095c5555fe083844281f6b093bb,canceled,2018-08-31 16:13:44,NaT,NaT,NaT,2018-10-01
99313,e9e64a17afa9653aacf2616d94c005b8,b4cd0522e632e481f8eaf766a2646e86,processing,2018-01-05 23:07:24,2018-01-09 07:18:05,NaT,NaT,2018-02-06
99347,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,NaT,NaT,NaT,2018-09-27
99348,a69ba794cc7deb415c3e15a0a3877e69,726f0894b5becdf952ea537d5266e543,unavailable,2017-08-23 16:28:04,2017-08-28 15:44:47,NaT,NaT,2017-09-15
99415,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,unavailable,2017-10-10 10:50:03,2017-10-14 18:35:57,NaT,NaT,2017-10-23

In [11]:
### MAIORES 20 CLIENTES  ###
top_10_custormers = orders['customer_id'].value_counts()[:20]
top_10_custormers

customer_id
9ef432eb6251297304e76186b10a928d    1
b0830fb4747a6c6d20dea0b8c802d7ef    1
41ce2a54c0b03bf3443c3d931a367089    1
f88197465ea7920adcdbec7375364d82    1
8ab97904e6daea8866dbdbc4fb7aad2c    1
503740e9ca751ccdda7ba28e9ab8f608    1
ed0271e0b7da060a393796590e7b737a    1
9bdf08b4b3b52b5526ff42d37d47f222    1
f54a9f0e6b351c431402b8461ea51999    1
31ad1d1b63eb9962463f764d4e6e0c9d    1
494dded5b201313c64ed7f100595b95c    1
7711cf624183d843aafe81855097bc37    1
d3e3b74c766bc6214e0c830b17ee2341    1
19402a48fe860416adf93348aba37740    1
3df704f53d3f1d4818840b34ec672a9f    1
3b6828a50ffe546942b7a473d70ac0fc    1
738b086814c6fcc74b8cc583f8516ee3    1
3187789bec990987628d7a9beb4dd6ac    1
059f7fc5719c7da6cbafe370971a8d70    1
7f8c8b9c2ae27bf3300f670c3d478be8    1
Name: count, dtype: int64

In [12]:
agrupado = orders['customer_id'].describe()
agrupado

count                                99441
unique                               99441
top       9ef432eb6251297304e76186b10a928d
freq                                     1
Name: customer_id, dtype: object

In [13]:
agrupado = orders['order_purchase_timestamp'].describe()
agrupado

count                            99441
mean     2017-12-31 08:43:12.776581120
min                2016-09-04 21:15:19
25%                2017-09-12 14:46:19
50%                2018-01-18 23:04:36
75%                2018-05-04 15:42:16
max                2018-10-17 17:30:18
Name: order_purchase_timestamp, dtype: object

In [14]:
orders_per_month_year = (
    orders
    .assign(
        ano=orders["order_purchase_timestamp"].dt.year,
        mes=orders["order_purchase_timestamp"].dt.month
    )
    .groupby(["ano", "mes"], as_index=False)
    .size()
    .rename(columns={"size": "quantidade"})
)

orders_per_month_year

     ano  mes  quantidade
0   2016    9           4
1   2016   10         324
2   2016   12           1
3   2017    1         800
4   2017    2        1780
5   2017    3        2682
6   2017    4        2404
7   2017    5        3700
8   2017    6        3245
9   2017    7        4026
10  2017    8        4331
11  2017    9        4285
12  2017   10        4631
13  2017   11        7544
14  2017   12        5673
15  2018    1        7269
16  2018    2        6728
17  2018    3        7211
18  2018    4        6939
19  2018    5        6873
20  2018    6        6167
21  2018    7        6292
22  2018    8        6512
23  2018    9          16
24  2018   10           4

In [15]:
# datetime mensal
orders_per_month_year["data"] = pd.to_datetime(
    orders_per_month_year["ano"].astype(str) + "-" +
    orders_per_month_year["mes"].astype(str) + "-01"
)

# agregado por ano
por_ano = (
    orders_per_month_year
    .groupby("ano", as_index=False)["quantidade"]
    .sum()
)

# agregado por mês (todos os anos juntos)
por_mes = (
    orders_per_month_year
    .groupby("mes", as_index=False)["quantidade"]
    .sum()
)

from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(
    rows=1,
    cols=3,
    subplot_titles=[
        "Evolução Mensal",
        "Total por Ano",
        "Distribuição por Mês"
    ]
)

# 1️⃣ Evolução mensal
fig.add_trace(
    go.Scatter(
        x=orders_per_month_year["data"],
        y=orders_per_month_year["quantidade"],
        mode="lines+markers",
        name="Mensal"
    ),
    row=1, col=1
)

# 2️⃣ Total por ano
fig.add_trace(
    go.Bar(
        x=por_ano["ano"],
        y=por_ano["quantidade"],
        name="Ano"
    ),
    row=1, col=2
)

# 3️⃣ Distribuição por mês
fig.add_trace(
    go.Bar(
        x=por_mes["mes"],
        y=por_mes["quantidade"],
        name="Mês"
    ),
    row=1, col=3
)

fig.update_layout(
    height=450,
    showlegend=False,
    title_text="Análise Temporal de Pedidos",
    margin=dict(l=20, r=20, t=60, b=20)
)

fig.show()